### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ale5000-git**
Minor fixes to the README
Added Android 7
Include most of the changes of @KAMiKAZOW at #95
Better separation for the lists of backends
Added special note for Nougat
Corrected name
Report last update year for unmaintained backends

---
This change is [Reviewable](https://reviewable.io/reviews/microg/android_packages_apps_unifiednlp/112)

### CODE REVIEW

**Comment by gdt** [comment]
I think this is mostly ok, but just adding Android 7.1.1 to the list of systems on which installation is straightforward seems wrong.  With CM 14.1, UnifiedNLP does not work, and self test shows it as not registered in system.  I did root/remount and then mv of the directory from /data/apps to /system/priv-apps, and then after reboot it was fine.

**Comment by gdt** [comment]
I wonder if for backends that are unmaintained they should be listed in a separate section "Obsolete backends" that has the comment "This backend has not been maintained since 201X and should not be used." or similar.

**Comment by gdt** [comment]
PersonalWifiBackend should be called LocalWifiNlpBackend, which is how it's labeled on f-droid, or perhaps LocalWiFiBackend, which is what you get from taking the spaces out of the title on the github README.md.   I have never seen the name Personal anyhere else.

**Review by AZA0098 — APPROVED** [review]
感謝

**Comment by ale5000-git** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/microg/android_packages_apps_unifiednlp/112#-K_5h01qn9yrbnnNzNWW:-K_5h01qn9yrbnnNzNWX:b-meqq31) (no related file):*
@gdt: Done.
@mar-v-in: Is it OK?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microg/android_packages_apps_unifiednlp/112)*

**Comment by mar-v-in** [comment]
Can you keep the copyright c as `(C)` instead, it works everywhere which is not true for the character

**Comment by mar-v-in** [comment]
Thanks!

**Review by DWoods24 — APPROVED** [review]

**Review by DWoods24 — COMMENTED** [review]
No way

**Pull request merged**
