### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by Gena95**
I just added Russian translation :)

### CODE REVIEW

**Comment by mar-v-in** [comment]
You should not add strings marked with translatable=false to a locale file (because this might break after future changes in the original)

**Comment by Gena95** [comment]
I just commented this strings for easy editing in feauture. Is this okay or just delete this strings?

**Comment by mar-v-in** [comment]
Better just delete them, these are internal strings that will be removed sooner or later anyway...

**Comment by Gena95** [comment]
Okay:)

**Pull request merged**
