### PR TITLE
Fix typo in strings

### PR DESCRIPTION
**Pull request by ArchangeGabriel**
Again, spotted while working on french translation.

This might require fixing in the other languages too (just checked Serbian, which is affected). I didn’t verified it for GmsCore either. Would you want me to check both and push commits to fix if necessary or will you handle it?

### CODE REVIEW

**Comment by mar-v-in** [comment]
Would be awesome if you can fix other typos as well, just push another PR (you can do it in the same PR as french translations). Thanks for this work btw!

**Comment by ArchangeGabriel** [comment]
Now that Transifex is used, should I fix it here or on Transifex? Because I can’t on the latter, unless adding every language to the one I can translate, which I don’t want to.

**Comment by mar-v-in** [comment]
I will continue to merge PRs for strings, Transifex is mostly to make some things easier

As I guess it was you to click the request button in Transifex: Is there any reason to use fr_FR instead of fr? AFAIK french is not too different between countries

**Comment by ArchangeGabriel** [comment]
Yes, that was me. This was because of a bug in Transifex that wouldn’t authorize me to join the project because it couldn’t recognize French (apparently because I had already been accepted for another project of the same organization). You can discard that, the differences between Québécois (CA French) and Français (FR French) are mostly irrelevant here. ;)

**Pull request merged**
