### PR TITLE
readme: clarify installation instructions

### PR DESCRIPTION
**Pull request by David-Guillot**
* ADB commands directly as Shell snippets
* Move Nougat to a separate case, since the KK/L/M procedure doesn't work

---
This change is [Reviewable](https://reviewable.io/reviews/microg/android_packages_apps_unifiednlp/146)

### CODE REVIEW

**Comment by ale5000-git** [comment]
It isn't true, the procedure for Nougat is the same as for other, there are just additional steps but the base is the same.

**Comment by David-Guillot** [comment]
The additional step you referring to (which i suppose is to apply the signature patch) is:
* neither properly documented (i just don't know what to type on my keyboard)
* nor acceptable from my perspective since Nougat is about to become the most widely used version of Android (and is probably already the most used AOSP version in the community of people installing custom ROMs) ; IMHO the most used version is supposed to be the rule, not the exception that you handle with a patch

This is why i decided to go for a manual ADB install (which is slightly different from KK/L/M because you apparently have to put the APK in a subfolder of `priv-app`, but i'm not sure about that, i read that on some blog posts), and then to share my experience through this README ;)

**Comment by ale5000-git** [comment]
L and M is the same of N

**Comment by JonnyTech** [comment]
To confirm, placing the file at `/system/priv-app/microg.apk` works on L, M, N and O.

**Comment by ale5000-git** [comment]
It works but it is only for compatibility I think:
Since Lollipop the structure is changed and who know for how much time the old structure will still work.

**Comment by David-Guillot** [comment]
Thanks @ale5000-git for the clarifications about the subfolder thing, i was not really sure.

@mar-v-in , what do you think about all this?

**Comment by ale5000-git** [comment]
I haven't tried but I don't think `adb mount /system` is even working, bwt too much separation will lead to more error when it need to be updated.
This evening I will see if I can make it more clear for all Android versions.

**Comment by David-Guillot** [comment]
Actually i replaced `adb remount` by `adb mount /system` because the former was not working with my configuration (Nougat, ADB from recovery). `adb root && adb remount` did not mount `/system`.

**Comment by ale5000-git** [comment]
I think it should be `adb **shell** mount /system`, bwt remount doesn't mount if not mounted as mount doesn't remount as read-write.
The command depend of what is needed.

**Comment by ale5000-git** [comment]
@mar-v-in: Is it possible to add a shell script?

In this way I can automatiuze some things.

**Comment by ale5000-git** [comment]
What do you think of this change? #147

**Comment by David-Guillot** [comment]
Actually @ale5000-git i don't really understand why you created another PR for this 😕. If some things don't seem clear enough in mine, i can fix it...

**Comment by ale5000-git** [comment]
Because I have taken a completely different approach

**Comment by David-Guillot** [comment]
Closing this as #147 seems more relevant, and the project doesn't seem maintained (i'm just cleaning up my Github :P ). Thanks @ale5000-git for credit in your PR ;)

**Pull request closed without merging**
